const test = require('node:test'); const assert = require('node:assert/strict'); const D=require('../src/Domain.js');
const p={performance_id:'P1',capacity:50}; const w=(q,s=D.STATES.WAITING)=>({performance_id:'P1',ticket_quantity:q,status:s});
test('1 availability calculation',()=>assert.equal(D.availability(p,[w(10),w(5,D.STATES.CONFIRMED),w(8,D.STATES.REJECTED)]),35));
test('2 booking within capacity succeeds',()=>assert.equal(D.assertQuantity(2),2));
test('3 over capacity fails',()=>assert.equal(D.availability(p,[w(51)]),0));
test('4 final available tickets can be booked',()=>assert.equal(D.availability(p,[w(49)]),1));
test('5 sold-out rejects inventory',()=>assert.equal(D.availability(p,[w(50)]),0));
test('6 waiting count protects concurrent submissions',()=>assert.equal(D.availability(p,[w(50,D.STATES.WAITING)]),0));
test('7 quantity positive integer only',()=>[0,-1,1.2,'x',''].forEach(x=>assert.throws(()=>D.assertQuantity(x))));
test('8 server price input requires validated quantity',()=>assert.equal(D.assertQuantity('3'),3));
test('9 waiting reserves inventory',()=>assert.equal(D.availability(p,[w(2)]),48));
test('10 confirmed does not change inventory reservation',()=>assert.equal(D.releaseRequired(D.STATES.WAITING,D.STATES.CONFIRMED),false));
test('11 rejected returns inventory',()=>assert.equal(D.releaseRequired(D.STATES.WAITING,D.STATES.REJECTED),true));
test('12 rejecting twice cannot return twice',()=>assert.equal(D.releaseRequired(D.STATES.REJECTED,D.STATES.REJECTED),false));
test('13 cancelled returns inventory once',()=>assert.equal(D.releaseRequired(D.STATES.CONFIRMED,D.STATES.CANCELLED),true));
test('14 status transition rules',()=>{assert.equal(D.canTransition(D.STATES.WAITING,D.STATES.CONFIRMED),true);assert.equal(D.canTransition(D.STATES.WAITING,D.STATES.REJECTED),true);assert.equal(D.canTransition(D.STATES.REJECTED,D.STATES.REJECTED),false)});
test('15 completed booking cannot retry transition',()=>assert.equal(D.canTransition(D.STATES.CONFIRMED,D.STATES.CANCELLED),false));
test('16 booking IDs are readable and unique by sequence',()=>{assert.equal(D.bookingCode('2026-08-21','17:00',1),'PAC-0821-1700-001');assert.notEqual(D.bookingCode('2026-08-21','17:00',1),D.bookingCode('2026-08-21','17:00',2))});
test('17 invalid booking sequence rejected',()=>assert.throws(()=>D.bookingCode('2026-08-21','17:00',0)));
test('18 formula injection neutralized',()=>assert.equal(D.escapeCell('=2+2'),"'=2+2"));
test('19 plain text preserved',()=>assert.equal(D.escapeCell('Ada'),'Ada'));
