/* PAC ticket booking M1. Sheet bookings are the capacity source of truth. */
var CONFIG = { SHEETS: { SETTINGS:'Settings', PERFORMANCES:'Performances', BOOKINGS:'Bookings', AUDIT:'AuditLog' }, MAX_SLIP_BYTES: 5 * 1024 * 1024, ALLOWED_MIME: ['image/jpeg','image/png','image/webp'] };
// Update this deliberately for each source change that needs live-deployment tracing.
var BUILD_ID = 'cae2371-json-config';
var HEADERS = {
  Settings:['key','value'],
  Performances:['performance_id','date','start_time','capacity','active'],
  Bookings:['internal_booking_id','booking_code','created_at','updated_at','performance_id','performance_date','performance_time','customer_name','customer_phone','ticket_quantity','price_per_ticket','total_amount','payment_slip_file_id','status','reviewed_at','reviewer','admin_note','request_id'],
  AuditLog:['timestamp','booking_code','previous_state','new_state','action','actor','metadata']
};
function doGet(e) { var page = e && e.parameter && e.parameter.page === 'admin' ? 'Admin' : 'Index'; var title='PAC Performance 2026'; try { if (spreadsheet_().getSheetByName(CONFIG.SHEETS.SETTINGS)) title=getSettings_().EVENT_NAME || title; } catch (ignored) {} var template=HtmlService.createTemplateFromFile(page); template.buildInfo=getBuildInfo(); return template.evaluate().setTitle(title); }
function include(name) { return HtmlService.createHtmlOutputFromFile(name).getContent(); }
function getBuildInfo() { var id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID') || ''; return { buildId:BUILD_ID, appVersion:'M1', spreadsheetIdSuffix:id ? id.slice(-6) : 'not-configured' }; }
function setup() {
  var ss = spreadsheet_(); Object.keys(HEADERS).forEach(function (name) { var sh = ss.getSheetByName(name) || ss.insertSheet(name); if (sh.getLastRow() === 0) sh.appendRow(HEADERS[name]); });
  var settings = { EVENT_NAME:'PAC Performance 2026', EVENT_DESCRIPTION:'University theatre performance', POSTER_URL:'', LOGO_URL:'', TICKET_PRICE:'120', BANK_NAME:'Krungthai Bank', BANK_ACCOUNT_NUMBER:'4673401352', BANK_ACCOUNT_HOLDER:'SET_ACCOUNT_HOLDER_NAME', SUPPORT_CONTACT:'SET_SUPPORT_CONTACT', TIMEZONE:'Asia/Bangkok', SLIP_FOLDER_ID:'' };
  var setSh = ss.getSheetByName(CONFIG.SHEETS.SETTINGS), existing = getSettings_(); Object.keys(settings).forEach(function(k){ if (!(k in existing)) setSh.appendRow([k, settings[k]]); });
  var perfSh = ss.getSheetByName(CONFIG.SHEETS.PERFORMANCES); if (perfSh.getLastRow() === 1) [['P-20260821-1700','2026-08-21','17:00',50,true],['P-20260821-1900','2026-08-21','19:00',50,true],['P-20260822-1700','2026-08-22','17:00',50,true],['P-20260822-1900','2026-08-22','19:00',50,true]].forEach(function(r){perfSh.appendRow(r);});
  if (!getSettings_().SLIP_FOLDER_ID) { var folder = DriveApp.createFolder('PAC Payment Slips'); setSetting_('SLIP_FOLDER_ID', folder.getId()); }
  return 'Setup complete. Configure account holder and support contact in Settings.';
}
function getPublicConfig() { var s=getSettings_(); return { eventName:s.EVENT_NAME, description:s.EVENT_DESCRIPTION, posterUrl:s.POSTER_URL, logoUrl:s.LOGO_URL, ticketPrice:Number(s.TICKET_PRICE), bankName:s.BANK_NAME, accountNumber:s.BANK_ACCOUNT_NUMBER, accountHolder:s.BANK_ACCOUNT_HOLDER, support:s.SUPPORT_CONTACT, performances:getPerformances_() }; }
// JSON avoids HTML Service object-serialization ambiguity and is validated in the browser.
function getPublicConfigJson() { return JSON.stringify(getPublicConfig()); }
function getPerformances_() { var bookings=getRows_(CONFIG.SHEETS.BOOKINGS); return getRows_(CONFIG.SHEETS.PERFORMANCES).filter(function(p){return String(p.active).toLowerCase() === 'true';}).map(function(p){ p.date=isoDate_(p.date); p.start_time=timeText_(p.start_time); p.capacity=Number(p.capacity); p.remaining=BookingDomain.availability(p,bookings); p.available=p.remaining>0; return p; }); }
function submitBooking(payload) {
  var lock=LockService.getScriptLock(); lock.waitLock(30000); try {
    validatePayload_(payload); var old=findByRequest_(payload.requestId); if(old) return success_(old);
    var performances=getPerformances_(), perf=performances.filter(function(p){return p.performance_id===payload.performanceId;})[0], qty=BookingDomain.assertQuantity(payload.quantity);
    if(!perf) throw new Error('This performance is no longer available.'); if(qty>perf.remaining) throw new Error('Only '+perf.remaining+' ticket(s) remain for this performance.');
    var slipId=saveSlip_(payload.slip), now=new Date(), code=nextCode_(perf), internal=Utilities.getUuid(), price=Number(getSettings_().TICKET_PRICE), total=price*qty;
    var row=[internal,code,now,now,perf.performance_id,perf.date,perf.start_time,BookingDomain.escapeCell(payload.name.trim()),BookingDomain.escapeCell(payload.phone.trim()),qty,price,total,slipId,BookingDomain.STATES.WAITING,'','','',payload.requestId];
    sheet_(CONFIG.SHEETS.BOOKINGS).appendRow(row); audit_(code,'',BookingDomain.STATES.WAITING,'BOOKING_CREATED','customer',JSON.stringify({quantity:qty,slipId:slipId})); return success_({booking_code:code,performance_date:perf.date,performance_time:perf.start_time,ticket_quantity:qty,total_amount:total,status:BookingDomain.STATES.WAITING});
  } finally { lock.releaseLock(); }
}
function lookupBooking(code, phone) { var b=getRows_(CONFIG.SHEETS.BOOKINGS).filter(function(x){return x.booking_code===String(code).trim() && String(x.customer_phone)===String(phone).trim();})[0]; if(!b) throw new Error('Booking not found.'); return {code:b.booking_code,performance:b.performance_date+' · '+b.performance_time,quantity:b.ticket_quantity,total:b.total_amount,status:friendly_(b.status)}; }
function getAdminDashboard(token) { requireAdmin_(token); var all=getRows_(CONFIG.SHEETS.BOOKINGS), ps=getPerformances_(); var count=function(s){return all.filter(function(b){return b.status===s;}).reduce(function(n,b){return n+Number(b.ticket_quantity);},0);}; return {performances:ps, total:ps.reduce(function(n,p){return n+p.capacity;},0), reserved:count(BookingDomain.STATES.WAITING)+count(BookingDomain.STATES.CONFIRMED), waiting:count(BookingDomain.STATES.WAITING), confirmed:count(BookingDomain.STATES.CONFIRMED), rejected:count(BookingDomain.STATES.REJECTED), queue:all.filter(function(b){return b.status===BookingDomain.STATES.WAITING;}).map(adminBooking_)}; }
// JSON avoids HTML Service object-serialization ambiguity for the admin dashboard too.
function getAdminDashboardJson(token) { return JSON.stringify(getAdminDashboard(token)); }
function reviewBooking(token, code, decision, note) { requireAdmin_(token); if([BookingDomain.STATES.CONFIRMED,BookingDomain.STATES.REJECTED].indexOf(decision)<0) throw new Error('Invalid decision.'); var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var sh=sheet_(CONFIG.SHEETS.BOOKINGS), rows=getRows_(CONFIG.SHEETS.BOOKINGS), b=rows.filter(function(x){return x.booking_code===code;})[0]; if(!b) throw new Error('Booking not found.'); if(b.status===decision) return {ok:true,idempotent:true}; if(!BookingDomain.canTransition(b.status,decision)) throw new Error('Booking has already been reviewed.'); var r=rows.indexOf(b)+2, now=new Date(), actor=Session.getActiveUser().getEmail() || 'authorized-admin'; sh.getRange(r,4).setValue(now); sh.getRange(r,14).setValue(decision); sh.getRange(r,15,1,3).setValues([[now,actor,BookingDomain.escapeCell(note||'')]]); audit_(code,b.status,decision,decision==='CONFIRMED'?'PAYMENT_CONFIRMED':'PAYMENT_REJECTED',actor,JSON.stringify({note:note||''})); if(BookingDomain.releaseRequired(b.status,decision)) audit_(code,b.status,decision,'CAPACITY_RELEASED',actor,'{}'); return {ok:true}; } finally {lock.releaseLock();} }
/** Reserved bookings may be cancelled by an authorized operator; duplicate calls are safe. */
function cancelBooking(token, code, note) { requireAdmin_(token); var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var sh=sheet_(CONFIG.SHEETS.BOOKINGS), rows=getRows_(CONFIG.SHEETS.BOOKINGS), b=rows.filter(function(x){return x.booking_code===code;})[0]; if(!b) throw new Error('Booking not found.'); if(b.status===BookingDomain.STATES.CANCELLED) return {ok:true,idempotent:true}; if([BookingDomain.STATES.WAITING,BookingDomain.STATES.CONFIRMED].indexOf(b.status)<0) throw new Error('This booking cannot be cancelled.'); var from=b.status,r=rows.indexOf(b)+2,now=new Date(),actor=Session.getActiveUser().getEmail()||'authorized-admin'; sh.getRange(r,4).setValue(now); sh.getRange(r,14).setValue(BookingDomain.STATES.CANCELLED); sh.getRange(r,15,1,3).setValues([[now,actor,BookingDomain.escapeCell(note||'')]]); audit_(code,from,BookingDomain.STATES.CANCELLED,'BOOKING_CANCELLED',actor,JSON.stringify({note:note||''})); audit_(code,from,BookingDomain.STATES.CANCELLED,'CAPACITY_RELEASED',actor,'{}'); return {ok:true}; } finally {lock.releaseLock();} }
function getSlipUrl(token, code) { requireAdmin_(token); var b=getRows_(CONFIG.SHEETS.BOOKINGS).filter(function(x){return x.booking_code===code;})[0]; if(!b || !b.payment_slip_file_id) throw new Error('Slip not found.'); return DriveApp.getFileById(b.payment_slip_file_id).getUrl(); }
function requireAdmin_(token) { var expected=PropertiesService.getScriptProperties().getProperty('ADMIN_TOKEN'); if(!expected) throw new Error('Admin is not configured: set Script Property ADMIN_TOKEN and deploy access within your university domain.'); if(!token || token!==expected) throw new Error('Unauthorized admin request.'); }
function validatePayload_(p) { if(!p || !p.requestId || !/^[a-zA-Z0-9_-]{16,100}$/.test(p.requestId)) throw new Error('Invalid request.'); if(!p.name || !String(p.name).trim()) throw new Error('Full name is required.'); if(!p.phone || !String(p.phone).trim()) throw new Error('Phone number is required.'); BookingDomain.assertQuantity(p.quantity); if(!p.slip) throw new Error('A payment slip image is required.'); if(CONFIG.ALLOWED_MIME.indexOf(p.slip.mimeType)<0 || p.slip.size>CONFIG.MAX_SLIP_BYTES || !p.slip.base64) throw new Error('Slip must be a JPEG, PNG, or WEBP image no larger than 5 MB.'); }
function saveSlip_(s) { var bytes=Utilities.base64Decode(s.base64), blob=Utilities.newBlob(bytes,s.mimeType,'slip-'+Utilities.getUuid()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[s.mimeType])); return DriveApp.getFolderById(getSettings_().SLIP_FOLDER_ID).createFile(blob).getId(); }
function nextCode_(p) { var prefix='PAC-'+String(p.date).replace(/-/g,'').slice(4)+'-'+String(p.start_time).replace(':','')+'-'; var n=getRows_(CONFIG.SHEETS.BOOKINGS).filter(function(b){return String(b.booking_code).indexOf(prefix)===0;}).length+1; return BookingDomain.bookingCode(p.date,p.start_time,n); }
function findByRequest_(id){return getRows_(CONFIG.SHEETS.BOOKINGS).filter(function(b){return b.request_id===id;})[0];} function success_(b){return {ok:true,bookingCode:b.booking_code,performance:(b.performance_date||'')+' · '+(b.performance_time||''),quantity:b.ticket_quantity,total:b.total_amount,status:'Payment slip waiting for review'};}
function spreadsheet_(){var id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID'); var ss=id ? SpreadsheetApp.openById(id) : SpreadsheetApp.getActive(); if(!ss) throw new Error('Set Script Property SPREADSHEET_ID to the ID of the Google Sheet for this ticket system.'); return ss;} function sheet_(n){return spreadsheet_().getSheetByName(n);} function getRows_(n){var sh=sheet_(n),v=sh.getDataRange().getValues(),h=v.shift();return v.filter(function(r){return r.join('')!=='';}).map(function(r){var o={};h.forEach(function(k,i){o[k]=r[i];});return o;});} function isoDate_(v){return Object.prototype.toString.call(v)==='[object Date]' ? Utilities.formatDate(v,'Asia/Bangkok','yyyy-MM-dd') : String(v);} function timeText_(v){return Object.prototype.toString.call(v)==='[object Date]' ? Utilities.formatDate(v,'Asia/Bangkok','HH:mm') : String(v);} function getSettings_(){var o={};getRows_(CONFIG.SHEETS.SETTINGS).forEach(function(r){o[r.key]=String(r.value);});return o;} function setSetting_(k,v){sheet_(CONFIG.SHEETS.SETTINGS).appendRow([k,v]);} function audit_(code,oldState,newState,action,actor,metadata){sheet_(CONFIG.SHEETS.AUDIT).appendRow([new Date(),code,oldState,newState,action,actor,metadata]);} function adminBooking_(b){return {code:b.booking_code,name:b.customer_name,phone:b.customer_phone,performance:b.performance_date+' · '+b.performance_time,quantity:b.ticket_quantity,total:b.total_amount,created:b.created_at,status:b.status};} function friendly_(s){return ({WAITING_PAYMENT_REVIEW:'Waiting for payment review',CONFIRMED:'Confirmed',REJECTED:'Rejected',CANCELLED:'Cancelled'})[s]||s;}
