/* PAC ticket booking M1. Sheet bookings are the capacity source of truth. */
var CONFIG = { SHEETS: { SETTINGS:'Settings', PERFORMANCES:'Performances', BOOKINGS:'Bookings', AUDIT:'AuditLog' }, MAX_SLIP_BYTES: 5 * 1024 * 1024, ALLOWED_MIME: ['image/jpeg','image/png','image/webp'] };
// Update this deliberately for each source change that needs live-deployment tracing.
var BUILD_ID = 'm2-promo-sales-cutoff';
var HEADERS = {
  Settings:['key','value'],
  Performances:['performance_id','date','start_time','capacity','active'],
  Bookings:['internal_booking_id','booking_code','created_at','updated_at','performance_id','performance_date','performance_time','customer_name','customer_phone','ticket_quantity','price_per_ticket','total_amount','payment_slip_file_id','status','reviewed_at','reviewer','admin_note','request_id','pricing_type','pricing_breakdown'],
  AuditLog:['timestamp','booking_code','previous_state','new_state','action','actor','metadata']
};
function doGet(e) { var page = e && e.parameter && e.parameter.page === 'admin' ? 'Admin' : 'Index'; var template=HtmlService.createTemplateFromFile(page); template.buildInfo=getBuildInfo(); var output=template.evaluate().setTitle('PAC Performance 2026'); output.append(page==='Admin' ? adminCsvClient_()+adminTheme_()+adminLoadingClient_() : customerLoadingClient_()); return output; }
function adminCsvClient_(){return '<script>(function(){function add(){var top=document.querySelector(".top");if(!top||document.getElementById("csvExport"))return;var b=document.createElement("button");b.id="csvExport";b.className="secondary";b.textContent="ส่งออก CSV";b.onclick=function(){var q=document.getElementById("q"),s=document.getElementById("status"),p=document.getElementById("perf"),o=document.getElementById("sort"),f={query:q?q.value:"",status:s?s.value:"",performanceId:p?p.value:"",sort:o?o.value:""};google.script.run.withSuccessHandler(function(raw){var r=JSON.parse(raw),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\\ufeff"+r.csv],{type:"text/csv;charset=utf-8"}));a.download=r.filename;a.click();URL.revokeObjectURL(a.href);}).getAdminCsvJson(token,f);};top.appendChild(b);}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",add);else add();})();</script>';}
function adminTheme_(){return '<style>@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@400;500;600;700;800&family=Pridi:wght@400;500;600;700&display=swap");:root{--bg:#14080a;--surface:#fffaf3;--ink:#271518;--muted:#816668;--accent:#8f1020;--soft:#f4e2dd;--ok:#2c674b;--warn:#915604;--danger:#9b1d2b;--border:#e2c9c2;--radius:14px}body{background:radial-gradient(circle at 8% 0,#50111b,#14080a 45%);font-family:"Noto Sans Thai",Tahoma,sans-serif}.shell{max-width:1220px;padding-top:32px}.top{padding:24px 0 18px;color:#fff4e9;border-bottom:1px solid #d9a17855}.top h1,.login h1,h2{font-family:Pridi,"Noto Sans Thai",serif;font-weight:600;letter-spacing:-.018em}.top h1{font-size:38px}.nav{gap:8px;padding:18px 0}.nav button{background:transparent;color:#f9dcd2;border:1px solid #b2756a77;box-shadow:none}.nav button:hover{background:#8f1020;border-color:#8f1020}.card{border:0;border-radius:14px;background:var(--surface);box-shadow:0 18px 42px #00000035;padding:22px}.login{background:linear-gradient(145deg,#fffaf3,#f6e6e0);border-top:4px solid #8f1020}.login h1{font-size:38px;color:#65101b}.grid{gap:12px}.metric{border:1px solid #e4ccc5;border-radius:10px;background:#fffdf9;padding:15px;min-height:94px}.metric b{font-family:Pridi,"Noto Sans Thai",serif;font-size:29px;color:#7e0f1e;line-height:1.05}.performance{padding:16px 0;border-top:1px solid #ead6d0}.performance:first-of-type{border-top:0}.progress{height:5px;background:#f0ded9}.progress i{background:#8f1020}.filters input,.filters select,textarea{border:1px solid #d8bdb7;border-radius:7px;background:#fffdf9;padding:12px}.booking{border-color:#e8d3cc;padding:18px 0}.booking h3{font-family:Pridi,"Noto Sans Thai",serif;font-size:21px;color:#72101d}.badge{background:#f8e7cd;color:#875207}.badge.ok{background:#e4f1e9;color:#286247}.badge.bad{background:#f8e4e5;color:#9b1d2b}button{background:#8f1020;border-radius:7px;box-shadow:0 4px 0 #620b15}button.secondary{background:#f3e2dc;color:#7d1020;box-shadow:none}.nav button.secondary{background:transparent;color:#f7d8cf;box-shadow:none}.nav button.secondary:hover{background:#8f1020}.modal{background:#110507cc}.modal-box{border-radius:14px;border-top:4px solid #8f1020;box-shadow:0 24px 65px #0009}.slip{border-radius:8px}.error{background:#f9e5e6;color:#8e2937;border-radius:8px}footer{color:#dfb6ad}@media(max-width:650px){.shell{padding:16px 12px}.top{padding-top:12px}.top h1{font-size:31px}.login{margin:7vh auto}.metric b{font-size:25px}.card{padding:18px}}</style>';}
function customerLoadingClient_(){return '<style>.promptpay-qr{display:none;margin:18px 0 0;padding-top:16px;border-top:1px solid #e4cfc8;text-align:center}.promptpay-qr.visible{display:block}.promptpay-qr img{display:block;width:min(100%,280px);margin:0 auto 10px;padding:6px;background:#fff;border-radius:8px;box-shadow:0 8px 20px #4a10161a}.promptpay-qr figcaption{font-weight:700;color:#79101e}.action-loading{position:fixed;inset:0;z-index:30;display:grid;place-items:center;padding:20px;background:#100607b8}.action-loading-box{width:min(420px,100%);padding:26px;border-top:4px solid #a61a2b;border-radius:14px;background:#fffaf3;box-shadow:0 24px 60px #0009;text-align:center}.action-spinner{width:36px;height:36px;margin:0 auto 14px;border:4px solid #ead1c8;border-top-color:#8f1020;border-radius:50%;animation:pacspin .8s linear infinite}@keyframes pacspin{to{transform:rotate(360deg)}}</style><div id="actionLoading" class="action-loading hidden" role="status" aria-live="polite"><div class="action-loading-box"><div class="action-spinner"></div><strong id="actionLoadingText">กำลังดำเนินการ…</strong><p class="muted">กรุณารอสักครู่</p></div></div><script>(function(){var oldInit=init,oldSubmit=submitBooking,oldSuccess=success,oldNotice=notice,oldLookup=lookup;function loader(on,text){var el=document.getElementById("actionLoading");if(!el)return;document.getElementById("actionLoadingText").textContent=text||"กำลังดำเนินการ…";el.classList.toggle("hidden",!on)}window.init=function(d){oldInit(d);var target=document.getElementById("promptpayQr");if(!target){target=document.createElement("figure");target.id="promptpayQr";target.className="promptpay-qr";target.innerHTML="<img id=\"promptpayQrImage\" alt=\"QR พร้อมเพย์สำหรับชำระเงิน\"><figcaption>สแกน QR พร้อมเพย์เพื่อชำระเงิน</figcaption>";document.querySelector("#step3 .summary").appendChild(target)}if(d.promptpayQr){document.getElementById("promptpayQrImage").src=d.promptpayQr;target.classList.add("visible")}else target.classList.remove("visible")};window.submitBooking=function(){if(slipData)loader(true,"กำลังส่งการจอง…");return oldSubmit()};window.success=function(r){loader(false);return oldSuccess(r)};window.notice=function(m,t){if(t==="error")loader(false);return oldNotice(m,t)};window.lookup=function(){loader(true,"กำลังตรวจสอบสถานะการจอง…");return oldLookup()};new MutationObserver(function(){var r=document.getElementById("lookupResult");if(r&&r.textContent.trim())loader(false)}).observe(document.getElementById("lookupResult"),{childList:true,subtree:true})})();</script>';}
function customerQrClient_(){return '<script>(function(){var timer=setInterval(function(){if(typeof cfg==="undefined"||!cfg||!cfg.promptpayQr)return;var target=document.getElementById("promptpayQr");if(!target){target=document.createElement("figure");target.id="promptpayQr";target.className="promptpay-qr";target.innerHTML="<img id=\"promptpayQrImage\" alt=\"PromptPay QR\"><figcaption>สแกน QR พร้อมเพย์เพื่อชำระเงิน</figcaption>";document.querySelector("#step3 .summary").appendChild(target)}document.getElementById("promptpayQrImage").src=cfg.promptpayQr;target.classList.add("visible");clearInterval(timer)},200)})();</script>';}
function adminLoadingClient_(){return '<style>.action-loading{position:fixed;inset:0;z-index:20;display:grid;place-items:center;padding:20px;background:#100607b8}.action-loading-box{width:min(380px,100%);padding:26px;border-top:4px solid #a61a2b;border-radius:14px;background:#fffaf3;box-shadow:0 24px 60px #0009;text-align:center}.action-spinner{width:36px;height:36px;margin:0 auto 14px;border:4px solid #ead1c8;border-top-color:#8f1020;border-radius:50%;animation:pacspin .8s linear infinite}@keyframes pacspin{to{transform:rotate(360deg)}}</style><div id="actionLoading" class="action-loading hidden" role="status" aria-live="polite"><div class="action-loading-box"><div class="action-spinner"></div><strong id="actionLoadingText">กำลังดำเนินการ…</strong><p class="muted">กรุณารอสักครู่</p></div></div><script>(function(){var oldRequest=request,oldDetail=detail,oldSlip=slip,oldCommit=commit,oldError=showError;function loader(on,text){var el=document.getElementById("actionLoading");if(!el)return;document.getElementById("actionLoadingText").textContent=text||"กำลังดำเนินการ…";el.classList.toggle("hidden",!on)}window.request=function(f){loader(true,"กำลังโหลดข้อมูล…");return oldRequest(f)};window.detail=function(c){loader(true,"กำลังเปิดรายละเอียด…");return oldDetail(c)};window.slip=function(c){loader(true,"กำลังเปิดสลิป…");return oldSlip(c)};window.commit=function(c,t){loader(true,t==="CONFIRMED"?"กำลังยืนยันการชำระเงิน…":"กำลังบันทึกรายการ…");return oldCommit(c,t)};window.showError=function(m){loader(false);return oldError(m)};new MutationObserver(function(){var m=document.getElementById("modal"),v=document.getElementById("view");if((m&&!m.classList.contains("hidden"))||(v&&v.textContent.indexOf("กำลังโหลดข้อมูล…")<0))loader(false)}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]})})();</script>';}
function customerQrRefreshClient_(){return '<script>(function(){function add(raw){var c;try{c=JSON.parse(raw)}catch(e){return}var url=c.promptpayQr||"https://drive.google.com/uc?export=view&id=13miykZnS92rk_cZ-a0IrZVyMecJIn8st",target=document.getElementById("promptpayQr");if(!target){target=document.createElement("figure");target.id="promptpayQr";target.className="promptpay-qr";target.innerHTML="<img id=\"promptpayQrImage\" alt=\"PromptPay QR\"><figcaption>สแกน QR พร้อมเพย์เพื่อชำระเงิน</figcaption>";document.querySelector("#step3 .summary").appendChild(target)}document.getElementById("promptpayQrImage").src=url;target.classList.add("visible")}function load(){if(!(window.google&&google.script&&google.script.run))return setTimeout(load,200);google.script.run.withSuccessHandler(add).getPublicConfigJson()}load()})();</script>';}
function customerStaticQr_(){ var src=''; try { src=promptpayQr_(getSettings_().PROMPTPAY_QR_FILE_ID); } catch (ignored) {} if (!src) return ''; return '<style>#pacStaticQr{display:none;position:fixed;right:18px;bottom:18px;z-index:12;width:154px;padding:8px;background:#fffaf3;border:2px solid #8f1020;border-radius:12px;box-shadow:0 14px 34px #0008;text-align:center}#pacStaticQr img{display:block;width:100%;height:auto}#pacStaticQr small{display:block;margin-top:4px;font-weight:700;color:#79101e}@supports selector(body:has(*)){body:has(#step3:not(.hidden)) #pacStaticQr{display:block}}@media(max-width:520px){#pacStaticQr{width:118px;right:10px;bottom:10px}}</style><aside id="pacStaticQr" aria-label="PromptPay QR"><img src="'+src+'" alt="PromptPay QR"><small>สแกนเพื่อชำระเงิน</small></aside>';}
function include(name) { return HtmlService.createHtmlOutputFromFile(name).getContent(); }
function getBuildInfo() { var id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID') || ''; return { buildId:BUILD_ID, appVersion:'M2', spreadsheetIdSuffix:id ? id.slice(-6) : 'not-configured' }; }
function setup() {
  var ss = spreadsheet_(); Object.keys(HEADERS).forEach(function (name) { var sh = ss.getSheetByName(name) || ss.insertSheet(name); if (sh.getLastRow() === 0) sh.appendRow(HEADERS[name]); else migrateHeaders_(sh,HEADERS[name]); });
  var settings = { EVENT_NAME:'PAC Performance 2026', EVENT_DESCRIPTION:'University theatre performance', POSTER_URL:'', LOGO_URL:'', TICKET_PRICE:'120', BASE_TICKET_PRICE:'120', PROMO_ENABLED:'true', PROMO_START_AT:'2026-08-14T00:00:00+07:00', PROMO_END_AT:'2026-08-16T23:59:59+07:00', PROMO_BUNDLE_SIZE:'2', PROMO_BUNDLE_PRICE:'200', BANK_NAME:'Krungthai Bank', BANK_ACCOUNT_NUMBER:'4673401352', BANK_ACCOUNT_HOLDER:'SET_ACCOUNT_HOLDER_NAME', PROMPTPAY_QR_FILE_ID:'', SUPPORT_CONTACT:'SET_SUPPORT_CONTACT', TIMEZONE:'Asia/Bangkok', SLIP_FOLDER_ID:'' };
  var setSh = ss.getSheetByName(CONFIG.SHEETS.SETTINGS), existing = getSettings_(); Object.keys(settings).forEach(function(k){ if (!(k in existing)) setSh.appendRow([k, settings[k]]); });
  var perfSh = ss.getSheetByName(CONFIG.SHEETS.PERFORMANCES); if (perfSh.getLastRow() === 1) [['P-20260821-1700','2026-08-21','17:00',50,true],['P-20260821-1900','2026-08-21','19:00',50,true],['P-20260822-1700','2026-08-22','17:00',50,true],['P-20260822-1900','2026-08-22','19:00',50,true]].forEach(function(r){perfSh.appendRow(r);});
  if (!getSettings_().SLIP_FOLDER_ID) { var folder = DriveApp.createFolder('PAC Payment Slips'); setSetting_('SLIP_FOLDER_ID', folder.getId()); }
  return 'Setup complete. Configure account holder and support contact in Settings.';
}
function getPublicConfig() { var s=getSettings_(), now=new Date(); return { eventName:s.EVENT_NAME, description:s.EVENT_DESCRIPTION, posterUrl:s.POSTER_URL, logoUrl:s.LOGO_URL, ticketPrice:Number(s.BASE_TICKET_PRICE||s.TICKET_PRICE), bankName:s.BANK_NAME, accountNumber:s.BANK_ACCOUNT_NUMBER, accountHolder:s.BANK_ACCOUNT_HOLDER, promptpayQr:promptpayQr_(s.PROMPTPAY_QR_FILE_ID), support:s.SUPPORT_CONTACT, pricing:publicPricing_(s,now), performances:getPerformances_(now) }; }
function imageDataUri_(fileId) { var blob=DriveApp.getFileById(fileId).getBlob(); var mime=blob.getContentType() || 'image/jpeg'; return 'data:'+mime+';base64,'+Utilities.base64Encode(blob.getBytes()); }
function promptpayQr_(fileId) { if (!fileId) return ''; try { return imageDataUri_(fileId); } catch (ignored) { return 'https://drive.google.com/thumbnail?id='+encodeURIComponent(fileId)+'&sz=w1000'; } }
// JSON avoids HTML Service object-serialization ambiguity and is validated in the browser.
function getPublicConfigJson() { return JSON.stringify(getPublicConfig()); }
function getPerformances_(now) { var bookings=getRows_(CONFIG.SHEETS.BOOKINGS), clock=now||new Date(); return getRows_(CONFIG.SHEETS.PERFORMANCES).filter(function(p){return String(p.active).toLowerCase() === 'true';}).map(function(p){ p.date=isoDate_(p.date); p.start_time=timeText_(p.start_time); p.capacity=Number(p.capacity); p.remaining=BookingDomain.availability(p,bookings); p.sales_close_at=BookingDomain.salesCloseAt(p); p.sales_state=BookingDomain.salesState(p,bookings,clock); p.available=p.sales_state==='AVAILABLE'; return p; }); }
function submitBooking(payload) {
  var lock=LockService.getScriptLock(); lock.waitLock(30000); try {
    validatePayload_(payload); var old=findByRequest_(payload.requestId); if(old) return success_(old);
    var now=new Date(), performances=getPerformances_(now), perf=performances.filter(function(p){return p.performance_id===payload.performanceId;})[0], qty=BookingDomain.assertQuantity(payload.quantity), settings=getSettings_();
    if(!perf) throw new Error('ไม่พบรอบการแสดงนี้'); if(perf.sales_state==='ONLINE_CLOSED') throw new Error('รอบนี้ปิดรับจองออนไลน์แล้ว กรุณาติดต่อซื้อบัตรหน้างาน'); if(perf.sales_state==='SOLD_OUT'||qty>perf.remaining) throw new Error('บัตรรอบนี้เต็มแล้ว');
    migrateHeaders_(sheet_(CONFIG.SHEETS.BOOKINGS),HEADERS.Bookings); var pricing=BookingDomain.calculateBookingPrice(qty,now,settings), slipId=saveSlip_(payload.slip), code=nextCode_(perf), internal=Utilities.getUuid();
    var row=[internal,code,now,now,perf.performance_id,perf.date,perf.start_time,BookingDomain.escapeCell(payload.name.trim()),BookingDomain.escapeCell(payload.phone.trim()),qty,pricing.effectiveUnitPrice,pricing.total,slipId,BookingDomain.STATES.WAITING,'','','',payload.requestId,pricing.pricingType,pricing.breakdown];
    sheet_(CONFIG.SHEETS.BOOKINGS).appendRow(row); audit_(code,'',BookingDomain.STATES.WAITING,'BOOKING_CREATED','customer',JSON.stringify({quantity:qty,slipId:slipId,pricingType:pricing.pricingType})); return success_({booking_code:code,performance_date:perf.date,performance_time:perf.start_time,ticket_quantity:qty,total_amount:pricing.total,status:BookingDomain.STATES.WAITING,pricing:pricing});
  } finally { lock.releaseLock(); }
}
function lookupBooking(code, phone) { var b=getRows_(CONFIG.SHEETS.BOOKINGS).filter(function(x){return x.booking_code===String(code).trim() && String(x.customer_phone)===String(phone).trim();})[0]; if(!b) throw new Error('ไม่พบข้อมูลการจอง กรุณาตรวจสอบรหัสและเบอร์โทรศัพท์'); return {code:b.booking_code,performance:BookingDomain.thaiDateTime(isoDate_(b.performance_date),timeText_(b.performance_time)),quantity:Number(b.ticket_quantity),total:Number(b.total_amount),status:friendly_(b.status),note:b.status===BookingDomain.STATES.REJECTED ? String(b.admin_note||'') : ''}; }
function getAdminDashboard(token) { return getAdminData_(token,{}); }
// JSON avoids HTML Service object-serialization ambiguity for the admin dashboard too.
function getAdminDashboardJson(token) { return JSON.stringify(getAdminDashboard(token)); }
/** M2 operational data. Filters are applied server-side and never expose token or Drive file IDs. */
function getAdminDataJson(token, filters) { return JSON.stringify(getAdminData_(token, filters||{})); }
function getAdminData_(token, filters) {
  requireAdmin_(token);
  var settings=getSettings_(), all=getRows_(CONFIG.SHEETS.BOOKINGS), ps=getPerformances_(), price=Number(settings.BASE_TICKET_PRICE||settings.TICKET_PRICE), metrics=BookingDomain.bookingMetrics(all,price);
  var selected=all.filter(function(b){ return (!filters.status || b.status===filters.status) && (!filters.performanceId || b.performance_id===filters.performanceId) && BookingDomain.matchBooking(b,filters.query); });
  var sort=filters.sort||'newest';
  selected.sort(function(a,b){ var av=dateMillis_(a.created_at),bv=dateMillis_(b.created_at); if(sort==='oldest') return av-bv; if(sort==='name') return String(a.customer_name).localeCompare(String(b.customer_name)); if(sort==='performance') return (String(a.performance_date)+String(a.performance_time)).localeCompare(String(b.performance_date)+String(b.performance_time)); return bv-av; });
  var performanceSummary=ps.map(function(p){ var rows=all.filter(function(b){return b.performance_id===p.performance_id;}), m=BookingDomain.bookingMetrics(rows,price); return {performanceId:p.performance_id,label:BookingDomain.thaiDateTime(p.date,p.start_time),capacity:p.capacity,remaining:p.remaining,reserved:p.capacity-p.remaining,waiting:m.waiting.tickets,confirmed:m.confirmed.tickets,salesState:p.sales_state,salesCloseAt:thaiTimestamp_(new Date(p.sales_close_at)),doorRemaining:p.remaining}; });
  return { eventName:settings.EVENT_NAME||'PAC Performance', price:price, pricing:publicPricing_(settings,new Date()), total:ps.reduce(function(n,p){return n+p.capacity;},0), reserved:metrics.waiting.tickets+metrics.confirmed.tickets, remaining:ps.reduce(function(n,p){return n+p.remaining;},0), metrics:metrics, performances:ps.map(function(p){return {performanceId:p.performance_id,label:BookingDomain.thaiDateTime(p.date,p.start_time)};}), performanceSummary:performanceSummary, bookings:selected.map(function(b){return adminBooking_(b,all);}) };
}
function getBookingDetailJson(token, code) { requireAdmin_(token); var all=getRows_(CONFIG.SHEETS.BOOKINGS), b=all.filter(function(x){return x.booking_code===String(code);})[0]; if(!b) throw new Error('ไม่พบรายการจอง'); return JSON.stringify(adminBooking_(b,all)); }
function getAdminCsvJson(token, filters) { var data=getAdminData_(token,filters||{}), columns=['รหัสการจอง','สถานะ','ชื่อลูกค้า','เบอร์โทรศัพท์','รอบการแสดง','จำนวนบัตร','ยอดชำระ','เวลาจอง','เวลาตรวจสอบ','ผู้ตรวจสอบ','หมายเหตุ']; var rows=data.bookings.map(function(b){return [b.code,b.statusLabel,b.name,b.phone,b.performance,b.quantity,b.total,b.created,b.reviewed,b.reviewer,b.note];}); return JSON.stringify({filename:'pac-bookings-'+Utilities.formatDate(new Date(),'Asia/Bangkok','yyyyMMdd-HHmm')+'.csv',csv:columns.map(BookingDomain.csvEscape).join(',')+'\r\n'+rows.map(function(r){return r.map(BookingDomain.csvEscape).join(',');}).join('\r\n')}); }
function publicPricing_(s,now){var p=BookingDomain.calculateBookingPrice(2,now,s);return {promoActive:p.promoActive,basePrice:Number(s.BASE_TICKET_PRICE||s.TICKET_PRICE),bundleSize:Number(s.PROMO_BUNDLE_SIZE||2),bundlePrice:Number(s.PROMO_BUNDLE_PRICE||200),startAt:s.PROMO_START_AT,endAt:s.PROMO_END_AT};}
function migrateHeaders_(sh,headers){var current=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getValues()[0];headers.forEach(function(h){if(current.indexOf(h)<0){sh.getRange(1,current.length+1).setValue(h);current.push(h);}});}
function reviewBooking(token, code, decision, note) { requireAdmin_(token); if([BookingDomain.STATES.CONFIRMED,BookingDomain.STATES.REJECTED].indexOf(decision)<0) throw new Error('Invalid decision.'); var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var sh=sheet_(CONFIG.SHEETS.BOOKINGS), rows=getRows_(CONFIG.SHEETS.BOOKINGS), b=rows.filter(function(x){return x.booking_code===code;})[0]; if(!b) throw new Error('Booking not found.'); if(b.status===decision) return {ok:true,idempotent:true}; if(!BookingDomain.canTransition(b.status,decision)) throw new Error('Booking has already been reviewed.'); var r=rows.indexOf(b)+2, now=new Date(), actor=Session.getActiveUser().getEmail() || 'authorized-admin'; sh.getRange(r,4).setValue(now); sh.getRange(r,14).setValue(decision); sh.getRange(r,15,1,3).setValues([[now,actor,BookingDomain.escapeCell(note||'')]]); audit_(code,b.status,decision,decision==='CONFIRMED'?'PAYMENT_CONFIRMED':'PAYMENT_REJECTED',actor,JSON.stringify({note:note||''})); if(BookingDomain.releaseRequired(b.status,decision)) audit_(code,b.status,decision,'CAPACITY_RELEASED',actor,'{}'); return {ok:true}; } finally {lock.releaseLock();} }
/** Reserved bookings may be cancelled by an authorized operator; duplicate calls are safe. */
function cancelBooking(token, code, note) { requireAdmin_(token); var lock=LockService.getScriptLock(); lock.waitLock(30000); try { var sh=sheet_(CONFIG.SHEETS.BOOKINGS), rows=getRows_(CONFIG.SHEETS.BOOKINGS), b=rows.filter(function(x){return x.booking_code===code;})[0]; if(!b) throw new Error('Booking not found.'); if(b.status===BookingDomain.STATES.CANCELLED) return {ok:true,idempotent:true}; if([BookingDomain.STATES.WAITING,BookingDomain.STATES.CONFIRMED].indexOf(b.status)<0) throw new Error('This booking cannot be cancelled.'); var from=b.status,r=rows.indexOf(b)+2,now=new Date(),actor=Session.getActiveUser().getEmail()||'authorized-admin'; sh.getRange(r,4).setValue(now); sh.getRange(r,14).setValue(BookingDomain.STATES.CANCELLED); sh.getRange(r,15,1,3).setValues([[now,actor,BookingDomain.escapeCell(note||'')]]); audit_(code,from,BookingDomain.STATES.CANCELLED,'BOOKING_CANCELLED',actor,JSON.stringify({note:note||''})); audit_(code,from,BookingDomain.STATES.CANCELLED,'CAPACITY_RELEASED',actor,'{}'); return {ok:true}; } finally {lock.releaseLock();} }
function getSlipUrl(token, code) { requireAdmin_(token); var b=getRows_(CONFIG.SHEETS.BOOKINGS).filter(function(x){return x.booking_code===code;})[0]; if(!b || !b.payment_slip_file_id) throw new Error('ไม่พบสลิป'); return imageDataUri_(b.payment_slip_file_id); }
function requireAdmin_(token) { var expected=PropertiesService.getScriptProperties().getProperty('ADMIN_TOKEN'); if(!expected) throw new Error('Admin is not configured: set Script Property ADMIN_TOKEN and deploy access within your university domain.'); if(!token || token!==expected) throw new Error('Unauthorized admin request.'); }
function validatePayload_(p) { if(!p || !p.requestId || !/^[a-zA-Z0-9_-]{16,100}$/.test(p.requestId)) throw new Error('Invalid request.'); if(!p.name || !String(p.name).trim()) throw new Error('Full name is required.'); if(!p.phone || !String(p.phone).trim()) throw new Error('Phone number is required.'); BookingDomain.assertQuantity(p.quantity); if(!p.slip) throw new Error('A payment slip image is required.'); if(CONFIG.ALLOWED_MIME.indexOf(p.slip.mimeType)<0 || p.slip.size>CONFIG.MAX_SLIP_BYTES || !p.slip.base64) throw new Error('Slip must be a JPEG, PNG, or WEBP image no larger than 5 MB.'); }
function saveSlip_(s) { var bytes=Utilities.base64Decode(s.base64), blob=Utilities.newBlob(bytes,s.mimeType,'slip-'+Utilities.getUuid()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[s.mimeType])); return DriveApp.getFolderById(getSettings_().SLIP_FOLDER_ID).createFile(blob).getId(); }
function nextCode_(p) { var prefix='PAC-'+String(p.date).replace(/-/g,'').slice(4)+'-'+String(p.start_time).replace(':','')+'-'; var n=getRows_(CONFIG.SHEETS.BOOKINGS).filter(function(b){return String(b.booking_code).indexOf(prefix)===0;}).length+1; return BookingDomain.bookingCode(p.date,p.start_time,n); }
function findByRequest_(id){return getRows_(CONFIG.SHEETS.BOOKINGS).filter(function(b){return b.request_id===id;})[0];} function success_(b){return {ok:true,bookingCode:b.booking_code,performance:(b.performance_date||'')+' · '+(b.performance_time||''),quantity:b.ticket_quantity,total:b.total_amount,status:'Payment slip waiting for review'};}
function spreadsheet_(){var id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID'); var ss=id ? SpreadsheetApp.openById(id) : SpreadsheetApp.getActive(); if(!ss) throw new Error('Set Script Property SPREADSHEET_ID to the ID of the Google Sheet for this ticket system.'); return ss;} function sheet_(n){return spreadsheet_().getSheetByName(n);} function getRows_(n){var sh=sheet_(n);if(!sh)throw new Error('ไม่พบชีต '+n+' กรุณารัน setup หนึ่งครั้ง');var v=sh.getDataRange().getValues(),h=v.shift();return v.filter(function(r){return r.join('')!=='';}).map(function(r){var o={};h.forEach(function(k,i){o[k]=r[i];});return o;});} function isoDate_(v){return Object.prototype.toString.call(v)==='[object Date]' ? Utilities.formatDate(v,'Asia/Bangkok','yyyy-MM-dd') : String(v).slice(0,10);} function timeText_(v){return Object.prototype.toString.call(v)==='[object Date]' ? Utilities.formatDate(v,'Asia/Bangkok','HH:mm') : String(v).slice(0,5);} function dateMillis_(v){return Object.prototype.toString.call(v)==='[object Date]' ? v.getTime() : new Date(v).getTime()||0;} function thaiTimestamp_(v){if(Object.prototype.toString.call(v)!=='[object Date]')return v?String(v):'-';return Utilities.formatDate(v,'Asia/Bangkok','d/M/yyyy HH:mm');} function getSettings_(){var o={};getRows_(CONFIG.SHEETS.SETTINGS).forEach(function(r){o[r.key]=String(r.value);});return o;} function setSetting_(k,v){sheet_(CONFIG.SHEETS.SETTINGS).appendRow([k,v]);} function audit_(code,oldState,newState,action,actor,metadata){sheet_(CONFIG.SHEETS.AUDIT).appendRow([new Date(),code,oldState,newState,action,actor,metadata]);} function adminBooking_(b,all){return {code:b.booking_code,name:String(b.customer_name||''),phone:String(b.customer_phone||''),performance:BookingDomain.thaiDateTime(isoDate_(b.performance_date),timeText_(b.performance_time)),performanceId:b.performance_id,quantity:Number(b.ticket_quantity),total:Number(b.total_amount),created:thaiTimestamp_(b.created_at),reviewed:thaiTimestamp_(b.reviewed_at),reviewer:String(b.reviewer||''),note:String(b.admin_note||''),status:b.status,statusLabel:friendly_(b.status),duplicate:all?BookingDomain.hasDuplicateActive(b,all):false};} function friendly_(s){return BookingDomain.statusLabel(s);}
